version: "3"

services:
  ros2:
    # specify where the Dockerfile you want to build is
    build: . 
    # allow using the terminal
    tty: true 
    # gives the container access to any devices connected to the computer
    privileged: true
    # use the computer's networking stack
    # necessary for two docker containers to be able to talk to each other in ROS2 
    network_mode: "host" # this 
    volumes:
      - ./catkin_ws:/root/mmint-rpi-an/catkin_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      # specify the display drivers
      - DISPLAY=$DISPLAY
      # if you want to specify a ros domain id (or other environment parameters) this is a good place
      # - ROS_DOMAIN_ID=2
      - ROS_MASTER_URI=http://192.168.1.128:11311
